// Alert Message Constants
export const createMessage = "Created Successfully !"
export const jobCreateMessage = "Created Successfully ! Verification link has been sent to the created email"
export const archivedMessage = "Archived Successfully !"
export const deleteMessage = "Deleted Successfully !"
export const titleActive = "can't be delete this inactive data";
export const editMessage = "Edited Successfully !"
export const savedMessage = "Saved Successfully !"
export const authenticateError = "Please authenticate"
export const candidateProfileError = "getting error while downloading the profile"
export const pricingPlansError = "error while getting subscription plans "
export const authenticateMessage = "Your session expired, Please login again to continue."
export const profileInvite = "Profiles have been successfully invited !"
export const appliedJob = "You have successfully applied for this job !"
export const widthDrawJob = "Your job application has been revoked."
export const passwordChanged = "Your Password has been changed."
export const passwordReset = "Your password had been updated! Please login with your updated password."
export const candidteRegister = "Your email address is successfully registered !"
export const registerSuccess = "Your email address is successfully registered! Check your mail for the verification link."
export const noResume = "Resume file not found !"
export const atleastOneRow = "Please select atleast one record !"
export const requiredFiled = "Please enter required fields !"
export const singleFileUpload = "Please upload only one file"
export const notificationMessage = "Notification sent successfully !"
export const fileUploadMessage = "File uploaded successfully !"
export const selectCheckboxMessage = "Please select atleast one record !"
export const emailVerifiedMessage = "Your email has been verified successfully !"
export const emailNotVerifiedMessage = "Your email is not verified! Please register again."

// Modal Text Constants
export const modalClose = "close";
export const modalTitle = "Are you sure?";
export const modalTextArchive = "This will archive the data.";
export const modalTextJobRole = "This will permanently delete the Job Role.";
export const modalTextProfile = "This will permanently delete the profile.";
export const modalInviteTextProfile = "You want to send invites to the selected profiles.";

// Tooltip Constants
export const tooltipCreateProfile = "Create Profile";
export const tooltipEmailSender = "Email Sender";
export const tooltipUploadResume = "Upload Resume";
export const tooltipDownloadProfileList = "Download Profile List";
export const tooltipImportProfile = "Import Profile";
export const tooltipExportTemplate = "Export Template";
export const tooltipAdvanceFilter = "Advance Filter";
export const tooltipSearchBox = "Search Box";
export const tooltipNlpSearchBox = "NLP search";
export const tooltipCloseSearchBox = "Close Search Box";
export const tooltipApplySearchBox = "Click To Search";
export const CVDownload = "CV Downloaded";
export const DownloadProfile = "Downloaded Profile List";
export const DownloadProfileCandidate = "profile downloaded";



// Headings Constants
export const headingAdvanceFilter = "Advance Filter"
export const headingDashboardChart = "Uploads Summary"
export const headingCandidateDashboardChart = "Profile Completed"
export const headingCreateProfile = "Create New Profile"
export const headingCreateRecruiter = "Create New Recruiter"
export const headingCreateOrganization = "Create New Organization"
export const headingCreateJobOpening = "Create New Job Opening"
export const headingCreateJobRole = "Create New Job Role"
export const headingEditProfile = "Edit Profile"
export const headingEditRecruiter = "Edit Recruiter"
export const headingEditOrganization = "Edit Organization"
export const headingEditJobOpening = "Edit Job Opening"
export const headingEditJobRole = "Edit Job Role"
export const headingShowApplicants = "Show Applicants"
export const headingShortlistApplicants = "Shortlist Applicants"
export const headingApplicantName = "Applicant Name"
export const headingChooseEductionalQualification = "Choose the eductional qualification";
export const headingChooseCurrentEmploymentStatus = "Choose the current employment status";
export const headingChoosePreferredLocation = "Choose the preferred location";
export const headingChooseIndustryType = "Choose the industry type";
export const headingChooseJobRole = "Choose the job role";
export const headingChooseCompanyName = "Choose the company name";
export const headingApplicantDetails = "Applicant Details"
export const headingBasicInformation = "Basic Information"
export const headingImportProfiles = "Import Profiles"
export const headingNotifyCandidates = "Notify Candidates"

// Placeholders Constants
export const placeholderNoResultsFound = "No results found";
export const placeholderSearch = "Search here...";
export const placeholderToList = "Enter email ids in To List";
export const placeholderBccList = "Enter email ids in Bcc List";
export const placeholderCcList = "Enter email ids in Cc List";
export const placeholderEmailBody = "Enter the email body";
export const placeholderSubject = "Enter the subject";
export const placeholderCandidateId = "Auto generate candidate Id";
export const placeholderJobRole = "Enter the job role";
export const placeholderDescription = "Enter the description";
export const placeholderName = "Enter the name";
export const placeholderFirstName = "Enter the first name";
export const placeholderLastName = "Enter the last name";
export const placeholderEmailID = "Enter the email id";
export const placeholderPhoneNo = "Enter the phone number";
export const placeholderCurrentLocation = "Enter the current location";
export const placeholderLocation = "Enter the location";
export const placeholderPresentAddress = "Enter the present address";
export const placeholderExperience = "Enter the experience";
export const placeholderPrimarySkills = "Enter the primary skills";
export const placeholderSecondarySkills = "Enter the secondary skills";
export const placeholderSkills = "Enter the skills";
export const placeholderCurrentCTC = "Enter the current CTC";
export const placeholderExpectedCTC = "Enter the expected CTC";
export const placeholderNoticePeriod = "Enter the notice period";
export const placeholderOrganization = "Enter the organization";
export const placeholderHeadline = "Enter the headline";
export const placeholderDesignation = "Enter the designation";
export const placeholderCurrentDesignation = "Enter the current designation";
export const placeholderCompanyLocation = "Enter the company location";
export const placeholderCompanyName = "Enter the company name";
export const placeholderCurrentCompany = "Enter the current company";
export const placeholderIndustry = "Enter the industry";
export const placeholderIndustryType = "Enter the industry type";
export const placeholderDepartment = "Enter the department";
export const placeholderResponsibilities = "Enter the responsibilities";
export const placeholderEductionalQualification = "Enter the eductional qualification";
export const placeholderShortJD = "Enter a Short JD (max 100 words)";
export const placeholderInstitute = "Enter the institute";
export const placeholderSpecialization = "Enter the specialization";
export const placeholderTotalOpenings = "Enter the total openings";
export const placeholderMinExperience = "Enter the min experience";
export const placeholderMaxExperience = "Enter the max experience";
export const placeholderTags = "Enter the tags";
export const placeholderAbout = "Describe about yourself";
export const placeholderAboutExperience = "Describe about the experience";
export const placeholderJobTitle = "Enter the job title";
export const placeholderDOB = "Enter the date of birth (ex: DD/MM/YYYY)";
export const placeholderDateOfJoining = "Enter the date of joining (ex: DD/MM/YYYY)";
export const placeholderLastEmployedDate = "Enter the last employed date (ex: DD/MM/YYYY)";
export const placeholderPassportValidity = "Enter the passport validity (ex: DD/MM/YYYY)";
export const placeholderPassingDate = "Enter the passing date (ex: DD/MM/YYYY)";
export const placeholderMarks = "Enter the marks (ex: XX%)";
export const placeholderChooseAdvanceFilter = "Choose advance filters";

// Labels Constants
export const labelPassword = "Password";
export const labelOldPassword = "Old Password";
export const labelNewPassword = "New Password";
export const labelConfirmPassword = "Confirm Password";
export const labelChangePassword = "Change Password";
export const labelResetPassword = "Reset Password";
export const labelApplicants = "Applicants";
export const labelOperator = "Operator";
export const labelEdit = "Edit";
export const labelCV = "CV";
export const labelShowHeaderFilter = "Show Header Filter";
export const labelSubject = "Subject";
export const labelCcList = "Cc List";
export const labelBccList = "Bcc List";
export const labelToList = "To List";
export const labelJobOpening = "Job Opening";
export const labelJobDescription = "Description";
export const labelJobDetails = "Job Details";
export const labelJobRole = "Job Role";
export const labelShortJD = "Short JD";
export const labelCurrentJobRole = "Currently I am working in this role";
export const labelName = "Name";
export const labelFirstName = "First Name";
export const labelLastName = "Last Name";
export const labelEmailID = "Email Id";
export const labelPhoneNo = "Phone Number";
export const labelPricingPlan = "Subscription";
export const labelExperience = "Experience (in Years)";
export const labelEmploymentType = "Employment Type";
export const labelEducation = "Education qualification";
export const labelEductionalQualification = "Education qualification";
export const labelDuration = "Duration";
export const labelWorkMode = "Work Mode";
export const labelSkills = "Skills";
export const labelPrimarySkills = "Primary Skills";
export const labelSecondarySkills = "Secondary Skills";
export const labelCurrentCTC = "Current CTC (in Lakhs)";
export const labelExpectedCTC = "Expected CTC (in Lakhs)";
export const labelCurrentEmploymentStatus = "Current Employment Status";
export const labelSubscription = "Subscription *";
export const labelNoticePeriod = "Notice Period (in Months)";
export const labelCompanyLocation = "Company Location";
export const labelLocation = "Location";
export const labelPostedOn = "Posted on";
export const labelCurrentLocation = "Current Location";
export const labelPreferredLocation = "Preferred Location";
export const labelReadyToRelocate = "Ready To Relocate";
export const labelOrganizationName = "Organization Name";
export const labelDesignation = "Designation";
export const labelCurrentDesignation = "Current Designation";
export const labelDescription = "Description";
export const labelActive = "Active";
export const labelDepartment = "Department";
export const labelIndustry = "Industry";
export const labelIndustryType = "Industry Type";
export const labelResponsibilities = "Responsibilities";
export const labelRequiredSkills = "Required Skills";
export const labelTotalOpenings = "Total Openings";
export const labelVisa = "Visa";
export const labelHavingPassport = "Having Passport";
export const labelPassportValidity = "Passport Validity";
export const labelOverseasExperience = "Overseas Experience";
export const labelMinExperience = "Min Experience";
export const labelMaxExperience = "Max Experience";
export const labelStatus = "Status";
export const labelPresentAddress = "Present Address";
export const labelTags = "Tags";
export const labelCandidateId = "Candidate Id (Auto Generated)";
export const labelDOB = "Date Of Birth";
export const labelMaritalStatus = "Marital Status";
export const labelCurrentCompany = "Current Company";
export const labelCompanyName = "Company Name";
export const labelAbout = "About Yourself";
export const labelJobTitle = "Job Title";
export const labelHeadline = "Headline";
export const labelQualification = "Qualification";
export const labelDateOfJoining = "Date Of Joining";
export const labelLastEmployedDate = "Last Employed Date";
export const labelInstitute = "Institute";
export const labelSpecialization = "Specialization";
export const labelPassingDate = "Passing Date";
export const labelMarks = "Marks In Percentage";
export const labelWithoutCv = "Without CV";
export const labelInvite = "Invite";
export const labelPublished = "Published";
export const labelDraft = "Draft";
export const labelArchive = "Archived";
export const labelAppliedDate = "Applied Date";
export const labelProfile = "Applicant Details";
export const labelCheckBox = "Check Box";
export const labelDelete = "Delete";
export const labelShowJobDetails = "Job Details";
export const labelCreatedBy = "Created By";
export const labelUpdatedBy = "Updated By";
export const labelUpdatedOn = "Updated On";
export const singleDragDrop = "Drag & drop file here to upload";
export const multipleDragDrop = "Drag & drop files here to upload";
export const singleBrowse = "or Browse File to upload";
export const multipleBrowse = " or Browse Files to upload";
export const supportLimitDocPdf = "Supports DOC, DOCX, PDF with max size of 5 MB.";
export const supportFileSuggestion ="Email/Phone number in resume file should be same as your current profile";
export const supportLimitXls = "Supports XLSX, XLS.";
export const supportMsgError = "Please select the Upload button to upload files successfully.";
export const supportFileDocPdfError = "Please choose the correct type of file i.e. DOC, DOCX, or PDF.";
export const supportFileXlsError = "Please choose the correct type of file i.e. XLSX, or XLS.";
export const supportLimitError = "Please reduce the size of the files to the limit of 5 MB.";

// Buttons Constants
export const buttonCreateRecruiter = "Add Recruiter";
export const buttonCreateOrganization = "Add Organization";
export const buttonCreateJob = "Add Job Opening";
export const buttonCreateJobRole = "Add Job Role";
export const buttonCreateProfile = "Add Profile";
export const buttonUpdate = "Update";
export const buttonSave = "Save";
export const buttonNext = "Next";
export const buttonUpload = "Upload";
export const buttonCancel = "Cancel";
export const buttonApply = "Apply";
export const buttonClear = "Clear";
export const buttonSaveYourExperienceDetails = "Save Your Experience Details";
export const buttonSaveYourEducationDetails = "Save Your Education qualification Details";
export const buttonInvite = "Invite";
export const buttonSend = "Send";
export const buttonWithdraw = "Revoke";
export const candidateSignIn = "Login to apply"
export const candidateSignUp = "Register to apply"

// Extra Text Constants
export const processing = 'Processing...'
export const notUploaded = 'Not Uploaded'
export const uploaded = 'Uploaded'
export const singleResume = 'Upload Your Resume'
export const multipliResume = 'Upload Your Resumes'
export const pieEducationDetails = 'Education qualification Details'
export const pieNewUploadsByRecruiter = 'New Uploads By Recruiters'
export const pieExperienceDetails = 'Experience Details'
export const pieNewUploadsByCandidates = 'New Uploads By Candidates'
export const pieBasicDetails = 'Basic Details'
export const pieResumesDeactivated = 'Unprocessed Profiles'
export const pieProfessionalInformation = 'Professional Information'
